export const authActionTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOAD_PROFILE: "LOAD_PROFILE",
  LOGOUT: "LOGOUT",
};

export const videoActionTypes = {
  HOME_VIDEO_SUCCESS: "HOME_VIDEO_SUCCESS",
  HOME_VIDEO_FAIL: "HOME_VIDEO_FAIL",
  HOME_VIDEO_REQUEST: "HOME_VIDEO_REQUEST",
};

export const videoByIdActionTypes = {
  GET_VIDEO_BY_ID_SUCCESS: "GET_VIDEO_BY_ID_SUCCESS",
  GET_VIDEO_BY_ID_FAIL: "GET_VIDEO_BY_ID_FAIL",
  GET_VIDEO_BY_ID_REQUEST: "GET_VIDEO_BY_ID_REQUEST",
};
